
name: Docker Frontend CI

on:
  push:
    branches: ['docker']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: setting new values
        run: echo VITE_BASE_URL=${{ secrets.VITE_BASE_URL }} > .env
        
      - name: Build the Docker image
        run: docker build -t vaibhavrajnathchauhan/sports-academy-frontend:${{ github.run_number }} .
      - name: Pushing docker images
        run: |
          docker login -u ${{secrets.DOCKER_HUB_USER}} -p ${{secrets.DOCKER_HUB_PASSWORD}}
          docker push vaibhavrajnathchauhan/sports-academy-frontend:${{ github.run_number }}
      - name: Recreating docker container
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ec2-user
          key: ${{secrets.SERVER_KEY}}
          script: |
            cd sports-academy/production/frontend
            BE_TAG=${{ github.run_number }} docker-compose up -d
